### ISSUE TITLE
Doesn't Compile with JDK 1.8

### ISSUE THREAD

**Issue by jmenchacavr** [benjiman/expressions#1]
I installed JDK 1.8u25, and tried to compile this, but I errors like this:

``` java
test.java:132: error: cannot find symbol
        public final Named<String> Foo = get(() -> foo).set(value -> foo = value).named("Foo");
                                         ^
  symbol:   method get(()->foo)
  location: class ExplicitPropertyNames
```

**Comment by bladeoflight16** [comment]
You need to import the methods. You can see an example in [the tests](https://github.com/benjiman/expressions/blob/master/src/test/java/uk/co/benjiweber/expressions/PropertyTest.java):

```
import static uk.co.benjiweber.expressions.properties.Property.get;
import static uk.co.benjiweber.expressions.properties.Property.set;
```

Alternatively, you can just import the `Property` class and use `Property.set` and `Property.get`.
